/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CardLevel = "core_concept" | "example" | "knowledge";

export type Fsrsstateenum = "Learning" | "Relearning" | "Review";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Cards {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  level: Generated<CardLevel>;
  resource_section_id: string;
  updated_at: Generated<Timestamp>;
  variants: Json;
}

export interface DailyRevisions {
  created_at: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<string>;
  owner_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Memories {
  card_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  owner_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MemoriesOnDailyRevisions {
  created_at: Generated<Timestamp>;
  daily_revisions_id: string;
  memory_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MemoryParams {
  created_at: Generated<Timestamp>;
  due_easy: Timestamp;
  due_hard: Timestamp;
  due_harder: Timestamp;
  due_normal: Timestamp;
  fsrs_difficulty: number;
  fsrs_elapsed_days: number;
  fsrs_lapses: number;
  fsrs_last_review: Timestamp | null;
  fsrs_reps: number;
  fsrs_scheduled_days: number;
  fsrs_stability: number;
  fsrs_state: Fsrsstateenum;
  memory_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Resources {
  cover: string;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  intro: Generated<string>;
  name: string;
  published_at: Timestamp | null;
  short_description: Generated<string>;
  tint: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ResourceSections {
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  more_content: string | null;
  position: number;
  resource_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  apple_uid: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  family_name: string | null;
  given_name: string;
  google_uid: string | null;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  cards: Cards;
  daily_revisions: DailyRevisions;
  memories: Memories;
  memories_on_daily_revisions: MemoriesOnDailyRevisions;
  memory_params: MemoryParams;
  resource_sections: ResourceSections;
  resources: Resources;
  users: Users;
}
