// Generated by ts-to-zod
import { z } from "zod";

export const authNewAccessTokenRequestSchema = z.object({
  refreshToken: z.string(),
});

export const authNewAccessTokenResponseSchema = z.object({
  accessToken: z.string(),
});

export const authValidateOAuthRequestSchema = z
  .object({
    givenName: z.string(),
    email: z.string(),
  })
  .and(
    z.union([
      z.object({
        type: z.literal("google"),
        googleToken: z.string(),
      }),
      z.object({
        type: z.literal("apple"),
        appleToken: z.string(),
      }),
    ]),
  );

export const authValidateOAuthResponseSchema = z.object({
  refreshToken: z.string(),
  accessToken: z.string(),
  userId: z.string(),
});
