// Generated by ts-to-zod
import { z } from "zod";

import { cardWithMemorySchema } from "./card-schema";
import { resourceHeaderSchema } from "./ressource-schema";

export const cardWithMemoryAndResourceHeaderSchema = cardWithMemorySchema.and(
  z.object({
    resourceHeader: resourceHeaderSchema,
  }),
);

export const dailyRevisionsSchema = z.object({
  date: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Must be in YYYY-MM-DD format."),
  cards: z.array(cardWithMemoryAndResourceHeaderSchema),
});

export const dailyRevisionsGenerateRequestSchema = z.object({
  date: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Must be in YYYY-MM-DD format."),
});

export const dailyRevisionsGenerateResponseSchema = dailyRevisionsSchema;
