// Generated by ts-to-zod
import { z } from "zod";

export const memorySchema = z.object({
  id: z.string(),
  cardId: z.string(),
  memoryStatus: z.union([
    z.literal("new"),
    z.literal("review"),
    z.literal("forgotten"),
  ]),
});

export const memoryBeingRevisedSchema = z.object({
  memory: memorySchema,
  memoryStatusBefore: memorySchema.shape.memoryStatus,
  firstTime: z
    .object({
      goodInARow: z.number(),
      reviewCount: z.number(),
      failureCount: z.number(),
    })
    .optional(),
  forgotten: z
    .object({
      goodInARow: z.number(),
      reviewCount: z.number(),
      failureCount: z.number(),
    })
    .optional(),
});

export const memoryBeingRevisedWithKeySchema = memoryBeingRevisedSchema.and(
  z.object({
    key: z.string(),
  }),
);
