// Generated by ts-to-zod
import { z } from "zod";

export const memorySchema = z.object({
  id: z.string(),
  cardId: z.string(),
  memoryStatus: z.union([
    z.literal("new"),
    z.literal("review"),
    z.literal("forgotten"),
  ]),
});
