// Generated by ts-to-zod
import { z } from "zod";

import { cardWithMemorySchema } from "./card-schema";

export const resourceBlockSchema = z.union([
  z.object({
    type: z.literal("paragraph"),
    content: z.string(),
  }),
  z.object({
    type: z.literal("youtube"),
    youtubeId: z.string(),
  }),
  z.object({
    type: z.literal("title"),
    level: z.union([z.literal(1), z.literal(2), z.literal(3)]),
    content: z.string(),
  }),
  z.object({
    type: z.literal("image"),
    source: z.string(),
  }),
]);

export const resourceHeaderSchema = z.object({
  id: z.string(),
  name: z.string(),
  tint: z.number(),
});

export const resourceSchema = resourceHeaderSchema.and(
  z.object({
    originalUrl: z.string().nullable(),
    content: z.string(),
  }),
);

export const resourceWithCardsAndMemorySchema = resourceSchema.and(
  z.object({
    cards: z.array(cardWithMemorySchema),
  }),
);

export const resourceGetRequestSchema = z.object({
  id: z.string(),
});

export const resourceGetResponseSchema = resourceWithCardsAndMemorySchema;
