// Generated by ts-to-zod
import { z } from "zod";

const ressourceArraySchema = z.array(
  z.object({
    id: z.string(),
    name: z.string(),
  }),
);

export const userResourcesResponseSchema = z.object({
  continue: ressourceArraySchema,
  saveForLater: ressourceArraySchema,
  library: ressourceArraySchema,
  explore: ressourceArraySchema,
});

export const userCreateRequestSchema = z.object({
  url: z.string(),
});
